### ISSUE TITLE
Backend Calculation Mega Issue

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1474]
## Background

Currently we do lots of calculations shown to the user on the frontend. In most cases, the user downloads condition and population metrics separately, and then their browser aggregates the numbers on the frontend in typescript.

The reason we do this is because of the decision to use the Google Big Query SQL function as our method to combine datasets. 

Our current process for data analysis is the following 
1. Download data from an external data source, and use python and pandas to coerce the numbers to be ready to be merged with population numbers.  Then upload those numbers to a big query table. This is represented by the [ingest to bq](https://github.com/SatcherInstitute/health-equity-tracker/blob/main/airflow/dags/cdc_vaccination_county.py#L20-L23) operator on airflow.

2. Merge that dataset with the population dataset, and any other external big query datasets needed. This is represented by the [aggregator step](https://github.com/SatcherInstitute/health-equity-tracker/blob/main/airflow/dags/cdc_vaccination_county.py#L25-L27) on airflow.

3. Download the merged dataset, calculate the per100k, and any other metrics that require population numbers.

4. If its a national dataset, also download the standalone population dataset, and aggregate both the condition and population dataset to national numbers. Then merge and calculate all metrics.

## Problems with the current approach

1. This is *slow*. 

The [dataforge library](https://github.com/SatcherInstitute/health-equity-tracker/blob/281052a957b096a26aac28c79766a2be62d0c7dc/frontend/src/data/variables/CdcCovidProvider.ts#L1) we use as a pandas stand-in on the frontend is horribly inefficient. Earlier we found that merging the ACS population percentage to the covid data [causes some browsers to crash](https://github.com/SatcherInstitute/health-equity-tracker/issues/1202).  While we fixed that, we still see many operations using this library take a number of seconds on the frontend.

2. It makes it basically impossible to test our numbers end to end. 

Because we break our data analysis into three steps which need to be tested individually, and because the SQL aggregation steps CAN NOT be tested, we can not actually end to end test the per 100k numbers the user ends up actually seeing on the page. This is self evidently bad and makes adding any new metric to the page take longer and be scarier.

## Proposed Solution

We should go through conditions, one by one, and move every single calculation to the backend. 

## End State
This track of work will be complete when there is no more math being done on the frontend, and every number the user sees can be seen in big query.

## How will this move the needle on health equity?

It will make the site faster and work better on slower computers, which will improve access to the data. Also making end to end testing possible will lower the chance of mistakes in the numbers we show.

## Tasks:

- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1475
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1476
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1478
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1477
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1479
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1487
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1480
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1481
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1488
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1490
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1491
- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/2086
- [ ] https://github.com/SatcherInstitute/health-equity-tracker/issues/2083

**Comment by benhammondmusic** [comment]
This is awesome. I'm going to use this layout as a template option for future "Mega Issues" / Epics
