### ISSUE TITLE
Data Typing - Pandas, BigQuery, and JS

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1662]
## Tasks:
- [x] Confirm above assumptions / loose understandings
- [x] Confirm outlined plan is the simplest and most accurate
- [x] Created backend util fn that automatically generates the needed BigQuery dtypes

Refactor each data source, run pipelines, confirm frontend working:
- [x] cawp, svi, bjs, vera in #1912 
- [ ] covid
- [ ] covid vaxx all levels
- [ ] poverty / health insurance
- [ ] AHR
- [x] ACS / ACS2010
- [ ] Census Pop. Est. / Census Pop. Est. SC

## Background
Coordinating data types between Python, Pandas, BiqQuery, and JavaScript has been problematic. A lot of time is wasted in pipeline testing that can't be done locally to ensure correct types for all data

## What's Missing / Problems with the current approach
We would like to send 4 different types from our Python/Pandas dataframes to BiqQuery:
- floats (we would like our `_pct_share` metrics to include a single decimal value, e.g. `40.4%`
- ints (we would like our `_per_100k` rates to display as whole numbers, e.g. `345 per 100k`
- strings (all text, group labels, etc)
- boolean (used only for `race_includes_hispanic` but maybe this will be going away after #1474 is done

There are a few issues with our current approach due to BigQuery  and Panda quirks:
- Pandas doesn't like nullable `int` columns (meaning a column contains a mix of int values and `null` values). We can get around this using the newer `dtype='Int64'` in Pandas
- BigQuery seems to accept these `INT64` data just fine, and the BigQuery ui displays them being stored, however when we fetch them on the frontend it seems to cast BigQuery `INTEGER` (an alias for `INT64` I believe) to JS `string`. Confusingly, it seems to be casting BigQuery `FLOAT` as JS `number` which is exactly what we want. 
- The frontend has a section in `DataFetcher` dedicated to testing whether a cell value in a nullable column is `== null` and if so, explicitly setting it to `null`. Otherwise, it is casting to `Number()`. 

## Solution

if we set everything on Pandas writing to BQ to `FLOAT` when we import into the frontend it will handle all of the above issues. I believe we already have frontend code in place to explicitly include `.0` as needed for whole number `_pct_share` values, and it seems JS auto trims dangling `.0` by default, so we don't need to further cast these "`float`" values as whole numbers

## Screenshots / Mockups

Logging the .json response from DataFetcher (prior to any null casting) shows that floats come through as numbers but ints come through as strings. #193

<img width="1744" alt="Screen Shot 2022-07-11 at 11 10 12 AM" src="https://user-images.githubusercontent.com/41567007/178343648-cf595472-9f95-4206-89f1-86fd0aacd5b3.png">

## End State 

- All python data sources use a standardized util function that creates a dtype dict settings numbers to FLOAT and everything else to STRING. 
- Frontend reads data in directly, and doesn't need the `null` and `Number` casting step. JS auto-trims dangling `.0` and our components (Vega, etc) will add it back on as needed

## How will this move the needle on health equity?
Specifically how this will help advance health equity, and is possible who the target audience might be (policy influencers, non-technical users, etc)

Having a single, defined process to handle these issues will improve development speed on new data sources, make our data sets easier to work and more consistent, also less error prone.

**Comment by joshzarrabi** [comment]
@benhammondmusic thank you for this.

I think this is right and will greatly simplify our codebase. 

One thing, the backend refactor will not necessarily get rid of the `race_includes_hispanic` boolean. 

I think we should get moving on this.

**Comment by benhammondmusic** [comment]
> @benhammondmusic thank you for this.
> 
> 
> 
> I think this is right and will greatly simplify our codebase. 
> 
> 
> 
> One thing, the backend refactor will not necessarily get rid of the `race_includes_hispanic` boolean. 
> 
> 
> 
> I think we should get moving on this. 

Sounds good. Curious where you anticipate us needing the field? My understanding was that for sources where it's available we would add a new column "ethnicity" whose values would be "Hispanic" "non-Hispanic" "unknown"

**Comment by joshzarrabi** [comment]
We can get rid of it if we want but its not connected to the backend refactor.
