### ISSUE TITLE
Assorted issues from watching UX videos

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1852]
## Tasks:
- [x] hover tooltip doesn’t appear on multimaps for some reason. 
- [x] Need to swap some 0 per 00k for <1 per 100k on Vega too
- [x] #1907
- [x] we should organize our external data sources, perhaps promoting higher reputation sites higher (e.g. CDC, Census, etc to the top, and ProPublica lower down)
- [x] issues with the charts loading on the population card; I have personally experienced this as well
- [x] blog thumbnails still weren't loading on one person's machine after quite a while
- [x] #1908
- [x] phrase in missing data section "there is no" data implies there's no data ANYWHERE, when really we mean there is no data from the sources we have found. We could address that it's available for specific counties but not NATIONALLY at the county level for every county
