### ISSUE TITLE
Refactor disparity bar chart

### ISSUE THREAD

**Issue by eriwarr** [SatcherInstitute/health-equity-tracker#1879]
## Background
There are several issues in the current implementation of the disparity bar chart. 

- The file is about 500 lines of code, which makes it difficult to read. 
- The file does not use Vega's typing system, making it difficult to resolve bugs or determine how new code should be implemented. 
- Fixing the shrinking bar issue required many if statements to determine chart dimensions, i.e.( `width < 350`). We should implement a hook that will update the dimensions once the chart's width is changed, only at specific breakpoints.
- The disparity bar chart does not use the stacked property which causes unnecessary evaluation of re-renders of functions. 

## What's Missing / Problems with the current approach
Refactoring the file will improve readability and decrease time in resolving bugs associated with this file in the future. 

## Proposed Solution
My proposed solution is reorganizing the components into their files and creating a custom hook to determine the chart dimensions. 

## Tasks:

- [x] Create TSX files for chart, axes, legends, marks, and scales and TS files for constants, helpers, and types.
- [x] Create a use custom hook for chart dimensions. 
- [x] Remove stacked property.
