### ISSUE TITLE
EPIC: Get 2020 territory pops

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2049]
## Background

HET currently relies on population data from 2010 for the smallest territories

## What's Missing / Problems with the current approach

Obviously this data is out of date, and not as accurate as we would like. It also lacks data for the territory county equivalents

## Proposed Solution
- [x] add new pipeline `decia_2020` that makes data available on our backend #2036 
- [x] run pipeline to get it on PROD
- [ ] #2051 
- [ ] Frontend: update frontend dataset_ids to reflect correct source used, including data shown directly on frontend and also datasets used in calculations on the backend
- [ ] Frontend: update alert to explain where / when all data is coming from. Indicate that we have used non-NH races as _NH races for AS, GU, and MP where _NH races are not available. The number of people identifying as hispanic in these areas is extremely low, and using the numbers this way allows us to include these islands' populations in more of our calculations and reports

## End State 

All Census population data on the tracker (other than time-series data from 2010-2020) will be sourced from 2020 instead of 2010

## How will this move the needle on health equity?
Striving for accuracy and transparency in data collection and calculation is fundamental. Using more current numbers will improve accuracy and legitimacy for the important and often overlooked part of the country.
