### ISSUE TITLE
Flatten nested `Data Type`  topics

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2093]
## Background

It's very easy for the user to miss that a few of our topics have sub-data types. The toggle to changes this data type isn't anchored in the sticky header and overall easy to miss. 

## Proposed Solution

First step is to flatten all data types so that the data types appear as dropdown options. The toggle will automatically no longer be used, but the functionality is still in place should we get to the point where we think it's needed again (perhaps moved up into the sticky header like a normal filter)

## End State 

No topics will contain a data type toggle, all will be accessed directly from the dropdown menu

## How will this move the needle on health equity?

We want our users to be able to quickly and easily see the options available and navigate through to the data they want to see. 

## Tasks:
- [x] flatten COVID data types
- [x] flatten CAWP data types
- [x] remove added types for drug use, keep only the composite measure
