### ISSUE TITLE
Improve Vega Map Scale

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2137]
## Background

Previously, we switched from "quantile" to "quantize" #1575 to fix legend bunching which caused legends on the MapCard to be unreadable. Another benefit was the extreme outliers were more noticeable as they were a dramatically different color than the rest. 

## What's Missing / Problems with the current approach

This change unfortunately made the maps less "pretty", as the data points often fall into only a few of the buckets, rather than being evenly distributed across all color buckets. Ultimately the maps look more monochrome and less visually appealing

## Proposed Solution

- [x] switch back to "quantile" for the MapCard and MultiMap
- [x] Per @eriwarr 's idea: switch the legend layout on the MapCard to be more like the MultiMap, in other words don't use a horizontal bar divided into colors with the unit labels beneath (which will "bunch" when the buckets are very small ranges) and instead separate out the individual bucket colors into a vertical list. Likely we can remove the legend from within the ChoroplethMap in the MapCard and add in a distinct Legend component as we do for MultiMap. This could happen in the far right portion of the map card as discussed in #2119
- [x] refactor map title to be displayed as a React component rather than handling via Vega which should simplify code AND prevent existing bugs like #2131 ad #2118 
- [x] consider handling extreme lows and highs the same was `0` is handled for CAWP; removing those extremes from the scale calculation altogether and presenting them as new, even more extreme versions of our color scale
- [x] consider switching Vega scheme from `yellowgreen` to `darkgreen` other another more visually appealing scheme

## End State 

- Our MapCard maps will be more visually appealing, while also having more readable legends regardless of the uniformity of the data points. We may also have improved visibility of outliers as a stretch goal

## How will this move the needle on health equity?

We want to make the visual impact IMMEDIATE and not require people to slog through too much numerical data 

## Tasks:
- [ ]
