### ISSUE TITLE
create component: card menu

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2287]
# Tasks

- [ ]  Create body layout & style
- [ ]  Desktop
- [ ]  Tablet
- [ ]  Mobile
- [ ]  Typography: Active Header
- [ ]  Typography: Inactive Header
- [ ]  Typography: Active Subheader
- [ ]  Typography: Inactive Subheader
- [ ]  A11y checks

### Suggested Slugs
| Main page | Slug suggestion |
| --- | --- |
| Source Acquisition | /methodology/source-acquisition |
| Topic Definitions and Limitations | /methodology/topics |
| Behavioral Health | /methodology/topics/behavioral-health |
| Chronic Disease | /methodology/topics/chronic-disease |
| COVID-19 | /methodology/topics/covid |
| HIV | /methodology/topics/hiv |
| Political Determinants of Health | /methodology/topics/political-determinants-of-health |
| Social Determinants of Health | /methodology/topics/social-determinants-of-health |
| Data Method Definitions | /methodology/definitions |
| Metrics | /methodology/definitions/metrics |
| Condition Variables | /methodology/definitions/condition-variables |
| Races and Ethnicities | /methodology/definitions/races-and-ethnicities |
| Recommended Citation | /methodology/recommended-citation |
