### ISSUE TITLE
Integrate Suggestions from AECF - Gun Violence (Gen. Pop)

### ISSUE THREAD

**Issue by eriwarr** [SatcherInstitute/health-equity-tracker#3028]
## Background

- [x] Update the homicide data to include prevalence specifically among Black Men.
- [x] Remove the Non-Fatal Injuries category due to limited data, but note its absence in the methodology.
- [x] Add an alert about the issues with Legal Intervention data, including reporting, classification, and missing data problems.
- [x]  Address the error displayed on the rate map for the highest/lowest rates, where values less than 1 are shown as 0 instead of the actual value, for example, 0.5 is displayed as 0. (Can these be larger than per 100k since they mostly report as 0). 
- [x] Add a subheader to the rates over time and inequities over time charts to explain that data is disaggregated by race starting in 2018.
- [x] Consider adding an Accidental category.

Notes:
- Consider presenting rates larger than per 100k since many values report as 0.
- Explore options to examine race and gender for suicide. 

## What's Missing / Problems with the current approach
Specifically what this epic will achieve

## Proposed Solution
A clear and concise description of the initial approach

## Screenshots / Mockups
If applicable, add images for mockup purposes

## How will this move the needle on health equity?
Specifically how this will help advance health equity, and is possible who the target audience might be (policy influencers, non-technical users, etc)

## Tasks:
- [ ] Linked sub-issues #1234
- [ ]
